### ISSUE TITLE
Could you explain the copy-on-write integrity problem?

### ISSUE THREAD

**Issue by banerjs** [sinbad/lfs-folderstore#5]
I would like to use hard-linking instead of copies to link my LFS files (hard disk space is unfortunately at a premium for me in my particular application). From the README, you mention that there might be file integrity concerns regarding the hard-linking approach, and I was wondering if you could elaborate what those issues might be? I'd like to understand more before I look into changes that I might make to (my own fork of) `lfs-folderstore` in order to hard-link instead of copy (if this is possible?).

Some background:

1. I'm using `lfs-folderstore` to save my large files to a Dropbox folder. Dropbox is synchronizing those files in the background.
1. This will be on a Linux system. I will not need to work in Windows for this project.
1. This is my first foray into LFS and I haven't looked into the steps involved during a pull, push, or fetch from an LFS store.

I'd love to hear any intuition that you might have on why hard-linking would be a bad idea, or why it was a bad idea when you made `lfs-folderstore`

Thanks!

PS: This is a brilliant program. It "just worked" from the get-go. Brilliant!

**Comment by sinbad** [comment]
Sorry this is so late, I didn't realise I didn't have notifications turned on for this repo. 

The main reason for not using hard links is that the data model of LFS assumes that files are immutable. They are named based on the hash of their contents, so at no time after naming the file can the content change, otherwise it breaks that assumption. That rules out sharing storage via hard links between the working copy and the repo storage, which is the most common case of duplication. 

Now, potentially you could use hard links just for the repo side, so between the content of the .git/lfs folder and Dropbox in this case. You'd still have duplicates in the working copy but only one copy between the repo commits and Dropbox. I haven't explored this but it might make sense as an opt-in (there are limitations on hard links that can mean you can't always use them, e.g. across logical drives).

Although I used lfs-folderstore myself for a number of years, I've since moved to Gitea for our projects so I'm not working on it anymore so I won't be adding this myself, but in principle it's something you could add if you wanted.

**Comment by banerjs** [comment]
No worries and thanks for the clarification! Definitely understand the need to copy instead of link for checking out a working copy. I'll keep it in mind if I do make a change. For now, I have been ok by simply reducing the _number_ of large files and using `git lfs prune` aggressively to reduce duplicated space on disk: I'll probably continue like that until things become an issue.
