### ISSUE TITLE
Could you explain the installation process on Mac?

### ISSUE THREAD

**Issue by thegladscientist** [sinbad/lfs-folderstore#8]
Thanks so much for this helper, it's been of great use to me and my small teams. On Windows it is a seamless process, and makes working with videos so much easier. 

For Macs...I saw that you had mentioned testing it with success...what is the installation process? I have added the path to the downloaded "darwin" release using "sudo nano /etc/paths" but still receive an error when pushing as if it can't find the helper. 

Is there something missing? Wanted to ask this in case others had a similar issue when installing for Mac, as it might be a welcome addition to the readme. :) 

Thanks again for everything!

**Comment by sinbad** [comment]
Sorry for the late reply, I'm not sure why I'm not getting notifications for this. 

Mac is slightly more complicated because it has separate paths for the command line and GUI apps, so even if you add `lfs-folderstore` to your PATH in the terminal, it won't work in GUI apps. Probably the best way to cope with this is to set `lfs.customtransfer.lfs-folder.path` to an *absolute path* to `lfs-folderstore` instead of just the name. That saves messing around trying to get your PATH updated for both environment (I've stopped using Mac now and they kept changing how you do this anyway).

**Comment by Sharashino** [comment]
Any better/other solution for this?
Didn't manage to pull it off in any way on my mac Ventura 13.1

Currently nor adding to path nor giving an absolute path works.
Works flawless on pc tho...

**Comment by gedw99** [comment]
``` go install . ``` 

that will compile and place it on the path.

then git lfs can find it..

hope that helps.

**Comment by Sharashino** [comment]
Thank you, I was able to get it running!
Best regards!
